### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by airxiti2** [sergej-singer/ES-Update#1]
Shows this, when trying it;

```
C:\Users\paulm\Downloads\ES-Update-main\ES-Update-main>py "C:\Users\paulm\Downloads\ES-Update-main\ES-Update-main\es-update\__main__.py" "C:\Users\paulm\Euroscope\EDWW-Full-Package_20240613153542-240601-0001"
Processing C:\Users\paulm\Euroscope\EDWW-Full-Package_20240613153542-240601-0001\EDWW FIR - Bremen.prf
    Updated PROFILE.txt with PM_OBS
    Updated SYMBOLOGY.txt with
    Updated realname with Paul M
    Updated certificate with 1586069
    Updated password with
    Updated rating with 2
    Updated server with AUTOMATIC
    Updated tovatsim with 1
    Updated Ts3NickName with 1586069
    Updated Ts3G2APtt with
    Updated PlaybackMode with Windows Audio Session
    Updated PlaybackDevice with
    Updated CaptureMode with Windows Audio Session
    Updated CaptureDevice with
Processing C:\Users\paulm\Euroscope\EDWW-Full-Package_20240613153542-240601-0001\EDWW FIR - Maastricht.prf
    Updated PROFILE.txt with PM_OBS
    Updated SYMBOLOGY.txt with
Traceback (most recent call last):
  File "C:\Users\paulm\Downloads\ES-Update-main\ES-Update-main\es-update\__main__.py", line 153, in add_attribute
    data[attribute_line][2] = attribute
    ~~~~^^^^^^^^^^^^^^^^
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\paulm\Downloads\ES-Update-main\ES-Update-main\es-update\__main__.py", line 361, in <module>
    sys.exit(main(*sys.argv))
             ^^^^^^^^^^^^^^^
  File "C:\Users\paulm\Downloads\ES-Update-main\ES-Update-main\es-update\__main__.py", line 106, in main
    prf = add_attribute(
          ^^^^^^^^^^^^^^
  File "C:\Users\paulm\Downloads\ES-Update-main\ES-Update-main\es-update\__main__.py", line 156, in add_attribute
    data[attribute_line].append(attribute)
    ~~~~^^^^^^^^^^^^^^^^
IndexError: list index out of range


```
Python Version: 3.12.3
EuroScope Version: 3.2.3.2
Package: EDWW Full Package (completely new install; no update)

In the EDWW FIR - Bremen.prf it worked, just not in the others

**Comment by sergej-singer** [comment]
Hi, had the same problem. Classical Programmer mistake, when you accidentally defined a variable outside of the cycle. Try to download repository again, I committed that fix yesterday.
